baseURL = 'https://josephriddle.com/'
languageCode = 'en-us'
title = 'Joseph Riddle'
theme = 'PaperMod'
enableEmoji = true

[params]
  comments = true

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 10
[[menu.main]]
  identifier = 'ideas'
  name = 'Ideas'
  url = '/ideas/'
  weight = 20
[[menu.main]]
  identifier = 'tags'
  name = 'Tags'
  url = '/tags/'
  weight = 30
